services:
  postgres:
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh dev-start.sh
    ports:
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
